services:
  jupyter:
    build: .
    networks:
      - prod
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=prod"
      - "traefik.http.routers.simex-jupyter.rule=Host(`${TRAEFIK_URL}`)"
    command: ["start-notebook.py", "--PasswordIdentityProvider.hashed_password='${JUPYTER_PASSWORD_HASHED}'"]
    volumes:
      - ./notebooks:/home/jovyan/work

networks:
  prod:
    external: true
    name: ${TRAEFIK_NETWORK}