# Overall SimEx settings
# possible modes exploration (this one) and exploitation (mod with prob trees)
import os
import datetime
from dataclasses import dataclass, field

timestamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")


@dataclass
class SimexSettings:
    """Define variables for the settings of the Simex

    Attributes:
    instance_name (str): The settings instance name. No default value.
    do_plot: (bool): Enables plot in the modifier of the final modifier points. Default value is 'False'.
    extensive_search (bool): Enables complete exploration by setting modifier_data_point to 1 and
    enabling extensive iteration. Default value is 'False'.
    extensive_iteration (bool): Gets enabled when extensive search is True (TODO: Refactor) . Default value is 'False'.
    SimEx_mode (str): The mode of simex only exploration implemented. Default value 'exploration'.
    max_workers (int): The maximum number of parallel workers. Default value is '14'.
    domain_min_interval (int): The minimum of the input domain. Default value is '2500'
    domain_max_interval (int): The maximum of the input domain. Default value is '4000'
    modifier_incremental_unit (int): Minimal incremental unit is the smallest allowed step_size. Default value is set
    to '25'. Note: If extensive search True then minimal increment is set to '1'.
    modifier_data_point (int): Data point step size on the X axis in the first round. Default value is set to '100'.
    In next iterations modifier_data_point = modifier_data_point - modifier_incremental_unit until
    modifier_data_point < minimal_increment_unit.
    add_first_last_point (bool): Adding first and last point of the interval generated by the modifier.
    Default value is set to 'True'. Note: Smoothens the final function.
    vfs_threshold_y_fitting (int): Threshold on the y axis defining the objective function. Default value is set to '15'.
    vfs_threshold_y_relative (float): Relative threshold as a fraction of |y_predicted| (e.g. 0.05 = 5%). A point is
    unfit if |residual| > max(vfs_threshold_y_fitting, vfs_threshold_y_relative * |y_predicted|), so the absolute
    threshold acts as a floor. Set vfs_threshold_y_fitting to 0 for a purely relative threshold.
    Default value is set to '0.0' (disabled, absolute threshold only).
    vfs_threshold_x_interval (float): For unfit point expand by threshold_x_interval to each side to close unfit interval.
    Default value is set to '0.80'
    vfs_degree (int): Minimum degree for exploration. We start with polyfit in x^degree. Default value is set to '2'.
    vfs_max_deg (int): Max degree for exploration to which degree we try to fit function x^max_degree.
    Default value is set to '9'.
    vfs_early_stop (bool): If early_stop = True and improvement is not acceptable by increasing dimension, we stop.
    Default value set to 'True'.
    vfs_improvement_threshold (float): Sufficient improvement threshold (previous_mse - current_mse) >=
    improvement_threshold. Default value is set to '0.1'.
    vfs_penality_weight (int): Penalty for MSE to avoid overfitting with high dimension polynomial.
    Default value is set to '1'.
    vfs_x_labels (str): X axis label name validator graph. Default value is set to 'Traffic volume [veh/h]'.
    vfs_y_labels (str): Y axis label name validator graph. Default value is set to r'TTS [veh$\cdot$h]'.
    vfs_title (str): Title for validator graph. Default value is set to
    'Fitted Curve with unfit Intervals for {self.instance_name}'.
    vfs_figsize_x (int): X size of the figure. Default value is set to '12'.
    vfs_figsize_y (int): Y size of the figure. Default value is set to '6'.
    vfs_font_size (int): Font size validator graph. Default value is set to '12'.
    ops_x_labels (str): X labels on the final graph. Default value is set to 'Traffic volume [veh/h]'.
    ops_y_labels (str): Y labels on the final graph. Default value is set to r'TTS [veh$\cdot$h]'.
    ops_title (str): Title on the final graph. Default value is set to 'Optimal Curve for {self.instance_name}'.
    ops_figsize_x (int): Figure size on the final graph. Default value is set to '10'.
    ops_figsize_y (int): Figure size on the final graph. Default value is set to '5'.
    ops_linewidth (int): Linewidth on the final graph. Default value is set to '3'.
    ops_number_x_points (int): Number of x axis points for the final graph. Default value is set to '400'.
    ops_predicted_points (bool): Display predicted points on the final graph. Default value is set to 'True'.
    ops_sigmoid_tailing (bool): Enable sigmoid tailing smoothener. Default value is set to 'True'.
    ops_sigmoid_width (int): Sigmoid width for the sigmoid smoothening. Default value is set to '15'.
    ops_threshold_plot (bool): Plot y_threshold on the final graph. Default value is set to 'True'.
    results_dir (str): Name of the results directory. Default value is set to 'results_dir_{instance_name}-{timestamp}'.
    log_filename (str): Filename for the log file. Default name is set to 'LOG-{self.instance_name}'.
    csv_filename (str): Final csv filename with the results. Default name is set to 'simex_output-{instance_name}'.
    """
    instance_name: str
    do_plot: bool = False
    extensive_search: bool = False
    extensive_iteration: bool = False
    SimEx_mode: str = "exploration"
    max_workers: int = 14
    domain_min_interval: int = 2500
    domain_max_interval: int = 4000
    modifier_incremental_unit: int = 25
    modifier_data_point: int = 100
    add_first_last_points: bool = False  # Interval borders
    vfs_threshold_y_fitting: int = 15
    vfs_threshold_y_relative: float = 0.0
    vfs_threshold_x_interval: float = 0.80
    vfs_degree: int = 2
    vfs_max_deg: int = 9
    vfs_early_stop: bool = True
    vfs_improvement_threshold: float = 0.1
    vfs_penality_weight: int = 1
    vfs_x_labels: str = 'Traffic volume [veh/h]'
    vfs_y_labels: str = r'TTS [veh$\cdot$h]'
    vfs_figsize_x: int = 12
    vfs_figsize_y: int = 6
    vfs_font_size: int = 12
    vfs_title: str = field(init=False)
    ops_x_labels: str = 'Traffic volume [veh/h]'
    ops_y_labels: str = r'TTS [veh$\cdot$h]'
    ops_title: str = field(init=False)
    ops_figsize_x: int = 10
    ops_figsize_y: int = 5
    ops_linewidth: int = 3
    ops_number_x_points: int = 400
    ops_predicted_points: bool = True
    ops_sigmoid_tailing: bool = True
    ops_sigmoid_width: int = 15
    ops_threshold_plot: bool = True
    mgs_points_generated_total: int = 0
    mgs_points_generation_intervals: int = 0
    mgs_mod_iterations: int = 0
    results_dir: str = field(init=False)
    log_filename: str = field(init=False)
    csv_filename: str = field(init=False)

    def __post_init__(self):
        """ Define variables dependent on the instance name."""
        self.log_filename = f'LOG-{self.instance_name}'
        self.csv_filename = f'simex_output-{self.instance_name}'
        self.ops_title = f'Optimal Curve for {self.instance_name}'
        self.vfs_title = f'Fitted Curve with unfit Intervals for {self.instance_name}'
        self.results_dir = f'results_dir_{self.instance_name}-{timestamp}'


SUMO_CONFIG_FILENAME = "sumo_config.ini"
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

_DEFAULT_SUMO_PATHS = {"model_path": "",
                       "sumo_path": "",
                       "marl_root_path": "",
                       "marl_run": "0",
                       "marl_end": "6000",
                       "marl_vsl": "1",
                       "marl_model_path": "",
                       "marl_results_path": ""}


def find_sumo_config(config_file=None):
    """Find the SUMO config: argument, $SIMEX_SUMO_CONFIG, cwd and parents, examples/marl_vsl/."""
    explicit = config_file or os.getenv("SIMEX_SUMO_CONFIG")
    if explicit:
        explicit = os.path.abspath(os.path.expanduser(explicit))
        if not os.path.isfile(explicit):
            raise FileNotFoundError(f"SUMO config file not found: {explicit}")
        return explicit

    directory = os.getcwd()
    while True:
        candidate = os.path.join(directory, SUMO_CONFIG_FILENAME)
        if os.path.isfile(candidate):
            return candidate
        parent = os.path.dirname(directory)
        if parent == directory:
            break
        directory = parent

    candidate = os.path.join(_REPO_ROOT, "examples", "marl_vsl", SUMO_CONFIG_FILENAME)
    if os.path.isfile(candidate):
        return candidate
    return None


def _expand_path(value, is_dir=False):
    """Expand ~ and $VARS, add trailing '/' to directories."""
    if not value:
        return value
    value = os.path.expandvars(os.path.expanduser(value.strip()))
    if is_dir and not value.endswith("/"):
        value += "/"
    return value


def get_path(config_file=None):
    """Read SUMO/MARL paths from the config file."""
    import configparser

    sumovsls = dict(_DEFAULT_SUMO_PATHS)
    config_path = find_sumo_config(config_file)
    if config_path is None:
        return sumovsls

    sumo_config = configparser.ConfigParser()
    sumo_config.read(config_path)
    sumo = sumo_config["SUMO"] if sumo_config.has_section("SUMO") else {}
    marl = sumo_config["MARL"] if sumo_config.has_section("MARL") else {}

    sumovsls.update({
        "model_path": _expand_path(sumo.get("MODEL_PATH", ""), is_dir=True),
        "sumo_path": _expand_path(sumo.get("SUMO_PATH", "")),
        "marl_root_path": _expand_path(marl.get("ROOT_PATH", ""), is_dir=True),
        "marl_run": marl.get("RUN", sumovsls["marl_run"]),
        "marl_end": marl.get("END", sumovsls["marl_end"]),
        "marl_vsl": marl.get("VSL", sumovsls["marl_vsl"]),
        "marl_model_path": _expand_path(marl.get("MODEL_PATH", ""), is_dir=True),
        "marl_results_path": _expand_path(marl.get("RESULTS_PATH", ""), is_dir=True),
    })
    sumovsls["config_file"] = config_path
    return sumovsls

# Data and settings for log purposes #
# Logger Granularity Settings
# log_granularity:
# 0 only general stats
# 1 minimal log
# 2 medium
# 3 detailed)


lgs = {"log_granularity": 3}


try:
    _sumo_paths = get_path()
except FileNotFoundError as e:
    print(f"WARNING: {e}")
    _sumo_paths = dict(_DEFAULT_SUMO_PATHS)


@dataclass
class SumoVsl:
    model_path: str = _sumo_paths["model_path"]
    sumo_path: str = _sumo_paths["sumo_path"]
    marl_root_path: str = _sumo_paths["marl_root_path"]
    marl_run: int = int(_sumo_paths["marl_run"])
    marl_end: int = int(_sumo_paths["marl_end"])
    marl_vsl: int = int(_sumo_paths["marl_vsl"])
    marl_model_path: str = _sumo_paths["marl_model_path"]
    marl_results_path: str = _sumo_paths["marl_results_path"]


def load_sumo_config(config_file=None, verbose=True):
    """Reload the SUMO config into SumoVsl."""
    paths = get_path(config_file)
    SumoVsl.model_path = paths["model_path"]
    SumoVsl.sumo_path = paths["sumo_path"]
    SumoVsl.marl_root_path = paths["marl_root_path"]
    SumoVsl.marl_run = int(paths["marl_run"])
    SumoVsl.marl_end = int(paths["marl_end"])
    SumoVsl.marl_vsl = int(paths["marl_vsl"])
    SumoVsl.marl_model_path = paths["marl_model_path"]
    SumoVsl.marl_results_path = paths["marl_results_path"]

    if verbose:
        print(f"SUMO config: {paths.get('config_file', 'NOT FOUND (using empty defaults)')}")
        for name, path in [("sumo_path", SumoVsl.sumo_path),
                           ("model_path", SumoVsl.model_path),
                           ("marl_model_path", SumoVsl.marl_model_path),
                           ("marl_results_path", SumoVsl.marl_results_path)]:
            status = "ok" if path and os.path.exists(path) else "MISSING"
            print(f"  {name:<18} {status:<8} {path}")
    return paths
